# Generated by Django 6.0.3 on 2026-03-20 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20260319_0619'),
        ('store', '0005_rename_first_name_customer_given_name'),
    ]

    operations = [
    ]
