# Generated by Django 6.0.3 on 2026-03-20 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_merge_20260320_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='last_update',
            new_name='updated_at',
        ),
    ]
