# Generated by Django 6.0.3 on 2026-03-20 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_last_update_product_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='given_name',
            new_name='first_name',
        ),
    ]
