# Generated by Django 6.0.3 on 2026-03-20 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_given_name_customer_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='place_at',
            new_name='placed_at',
        ),
    ]
