# Generated by Django 6.0.3 on 2026-04-21 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_orderitem_order_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='Product',
            new_name='product',
        ),
    ]
